### PR TITLE
Add ciao tutorial

### PR DESCRIPTION
**Pull request by markdryan**
This commit adds a simple ciao tutorial that explains how to set up a
small cloud application with ciao.

Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>

### CODE REVIEW

**Comment by markdryan** [comment]
@rbradford  or @mcastelino could you check the IP tables rules at the bottom of the document?  They work for me but I'll like to double check they're correct.

**Review by mcastelino — APPROVED** [review]
LGTM

**Comment by mcastelino** [comment]
@markdryan a even more powerful tutorial would be for us to setup the VMs using ciao, and the containers using kubernetes within ciao. Here the static VM based workloads are managed by ciao and the scale up/down workloads are managed by k8s running within ciao.

**Comment by markdryan** [comment]
Yes, that's a nice idea.  If you can think of a use case I'll add it.

**Comment by markdryan** [comment]
@mcastelino I deleted the first ip table rule as it didn't seem to be needed.

$ sudo iptables -t nat -A POSTROUTING --out-interface 198.51.100.2 -j MASQUERADE

**Pull request merged**
